spring.application.name=backend
#Error Messages
Service.USER_ALREADY_EXISTS = "User with this email already exists."
Service.INVALID_CREDENTIALS = "Invalid Credentials."
Service.INVALID_PASSWORD = "Invalid password."
Service.USER_NOT_FOUND = "User not found from this id"

# Database properties
spring.datasource.url=jdbc:mysql://localhost:3306/skillswap_ai
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8764